# Generated by Django 5.0.14 on 2025-10-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="period",
            field=models.IntegerField(blank=True, help_text="Current period/quarter", null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="scheduled_time",
            field=models.DateTimeField(blank=True, help_text="Scheduled start time", null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="time_remaining",
            field=models.CharField(blank=True, help_text="Time remaining in period", max_length=20),
        ),
        migrations.AddField(
            model_name="team",
            name="external_id",
            field=models.CharField(
                blank=True, help_text="External API ID for this team", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("external_id__isnull", False), models.Q(("external_id", ""), _negated=True)
                ),
                fields=("league", "external_id"),
                name="unique_team_external_id",
            ),
        ),
    ]
