# Generated by Django 5.0.14 on 2025-10-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_game_period_game_scheduled_time_game_time_remaining_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="time_remaining",
            field=models.CharField(
                blank=True, default="", help_text="Time remaining in period", max_length=20
            ),
        ),
    ]
