# Generated by Django 5.0.14 on 2025-10-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_game_time_remaining"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="situation",
            field=models.JSONField(
                blank=True,
                help_text="Live game situation (balls, strikes, outs, pitcher, batter, bases, etc.)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("live", "Live"),
                    ("in_progress", "In Progress"),
                    ("final", "Final"),
                    ("postponed", "Postponed"),
                    ("cancelled", "Cancelled"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
    ]
