# Generated by Django 5.0.14 on 2025-10-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_game_situation_alter_game_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="box_score",
            field=models.JSONField(
                blank=True, help_text="Inning-by-inning line scores and game statistics", null=True
            ),
        ),
    ]
