# Generated by Django 5.0.14 on 2025-10-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_game_box_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="attendance",
            field=models.IntegerField(blank=True, help_text="Game attendance", null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="broadcast_info",
            field=models.JSONField(
                blank=True,
                help_text="Additional broadcast details (radio, streaming, etc.)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="broadcast_network",
            field=models.CharField(
                blank=True, default="", help_text="TV network (e.g., ESPN, ABC)", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="venue_capacity",
            field=models.IntegerField(blank=True, help_text="Venue capacity", null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="venue_city",
            field=models.CharField(blank=True, default="", help_text="Venue city", max_length=100),
        ),
        migrations.AddField(
            model_name="game",
            name="venue_name",
            field=models.CharField(
                blank=True, default="", help_text="Stadium/arena name", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="venue_state",
            field=models.CharField(
                blank=True, default="", help_text="Venue state/province", max_length=100
            ),
        ),
    ]
