# Generated by Django 5.0.14 on 2025-10-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_game_attendance_game_broadcast_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="away_pitcher_name",
            field=models.CharField(
                blank=True, default="", help_text="Away team starting pitcher", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="away_pitcher_stats",
            field=models.JSONField(
                blank=True, help_text="Away pitcher statistics (W-L, ERA, etc.)", null=True
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="home_pitcher_name",
            field=models.CharField(
                blank=True, default="", help_text="Home team starting pitcher", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="home_pitcher_stats",
            field=models.JSONField(
                blank=True, help_text="Home pitcher statistics (W-L, ERA, etc.)", null=True
            ),
        ),
    ]
